repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.86.0
    hooks:
      - id: terraform_fmt
        # only run when files under demo01 change
        files: ^module10-w44/demo01/.*\.(tf|tfvars|tfvars.json)$
      - id: terraform_validate
        files: ^module10-w44/demo01/.*\.(tf|tfvars|tfvars.json)$
      - id: terraform_tflint
        files: ^module10-w44/demo01/.*\.(tf|tfvars|tfvars.json)$
      - id: terraform_checkov
        files: ^module10-w44/demo01/.*