name: Azure live tests — TFLint & Checkov

on:
  workflow_dispatch:
    inputs:
      resource_group:
        description: "Resource group containing the storage account"
        required: false
        default: "rg-tfstate-shs"
      storage_account:
        description: "Storage account name"
        required: false
        default: "sttfstateshs"
      container:
        description: "Blob container name"
        required: false
        default: "tfstate"
      workdir:
        description: "Terraform working directory to lint/scan (relative to repo root)"
        required: false
        default: "module9/buildOnce-deployMany/terraform"

permissions:
  id-token: write
  contents: read

jobs:
  validate-live:
    name: Validate live environment — tflint & checkov
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, test, prod]
      fail-fast: false
    concurrency:
      group: live-tests-${{ github.ref }}-${{ matrix.environment }}
      cancel-in-progress: true
    env:
      # RESOURCE_GROUP is computed per-matrix job below
      RESOURCE_GROUP: rg-${{ matrix.environment }}-shs
      STORAGE_ACCOUNT: ${{ github.event.inputs.storage_account }}
      CONTAINER: ${{ github.event.inputs.container }}
      WORKDIR: ${{ github.event.inputs.workdir }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: false
          environment: azurecloud
          allow-no-subscriptions: false
          audience: api://AzureADTokenExchange
          auth-type: SERVICE_PRINCIPAL
        env:
          RESOURCE_GROUP: rg-tfstate-shs
          STORAGE_ACCOUNT: sttfstateshs
          CONTAINER: tfstate
          WORKDIR: module9/buildOnce-deployMany/terraform

      - name: Verify storage account exists
        run: |
          echo "Checking storage account: $STORAGE_ACCOUNT in RG: $RESOURCE_GROUP"
          az storage account show -g "$RESOURCE_GROUP" -n "$STORAGE_ACCOUNT" --query "{name:name,resourceGroup:resourceGroup,minimumTlsVersion:minimumTlsVersion,allowBlobPublicAccess:allowBlobPublicAccess}" -o table

      - name: Verify blob container exists (using Azure AD auth)
        run: |
          echo "Checking container: $CONTAINER in storage account: $STORAGE_ACCOUNT"
          az storage container show --account-name "$STORAGE_ACCOUNT" --name "$CONTAINER" --auth-mode login || (echo "Container $CONTAINER not found in $STORAGE_ACCOUNT" && exit 1)

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: Run TFLint
        run: |
          echo "Running tflint in $WORKDIR"
          tflint --init
          tflint --chdir "$WORKDIR"

      - name: Install Checkov
        run: |
          python3 -m pip install --upgrade pip
          pip install checkov

      - name: Run Checkov
        run: |
          echo "Running Checkov against $WORKDIR"
          checkov -d "$WORKDIR" --framework terraform
