name: Oblig2 Terraform CI

on:
  pull_request:
    branches: 
      - main
    paths:
      - "module9/buildOnce-deployMany/terraform/**"

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  validate:
    runs-on: ubuntu-latest
    environment: dev
    env:
      WORKDIR: "module9/buildOnce-deployMany/terraform"
      BACKEND_HCL: "module9/buildOnce-deployMany/terraform/shared/backend.hcl"
      TF_INPUT: "false"
      TF_IN_AUTOMATION: "true"
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.3
          terraform_wrapper: false

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Export ARM_* for Terraform (OIDC)
        run: |
          {
            echo "ARM_USE_OIDC=true"
            echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}"
            echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}"
            echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          } >> "$GITHUB_ENV"

      - name: Terraform Format Check
        working-directory: ${{ env.WORKDIR }}
        id: fmt
        run: terraform fmt -check -recursive
        continue-on-error: true

      - name: Terraform Init
        working-directory: ${{ env.WORKDIR }}
        id: init
        run: |
          terraform init \
            -backend-config="../shared/backend.hcl" \
            -backend-config="key=oblig2/dev/dev.tfstate" \
            -input=false \
            -no-color
      
      - name: Terraform Validate
        working-directory: ${{ env.WORKDIR }}
        id: validate
        run: terraform validate -no-color
      
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: Run TFLint
        run: |
          tflint --init
          tflint --chdir "${{ env.WORKDIR }}/terraform"

      - name: Install Checkov
        run: python3 -m pip install --upgrade pip && pip install checkov

      - name: Run Checkov
        run: checkov -d "${{ env.WORKDIR }}/terraform" --framework terraform --quiet
        
  plan-all-environments:
    name: Plan - ${{ matrix.environment }}
    runs-on: ubuntu-latest
    needs: validate
    environment: ${{ matrix.environment }}
    env:
      WORKDIR: "module9/buildOnce-deployMany/terraform"
      BACKEND_HCL: "module9/buildOnce-deployMany/terraform/shared/backend.hcl"
      TF_INPUT: "false"
      TF_IN_AUTOMATION: "true"
    
    strategy:
      matrix:
        environment: [dev, test, prod]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.3
          terraform_wrapper: false
      
      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Export ARM_* for Terraform (OIDC)
        run: |
          {
            echo "ARM_USE_OIDC=true"
            echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}"
            echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}"
            echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          } >> "$GITHUB_ENV"
      
      - name: Terraform Init
        working-directory: ${{ env.WORKDIR }}
        run: |
          terraform init \
            -backend-config="../shared/backend.hcl" \
            -backend-config="key=oblig2/${{ matrix.environment }}/${{ matrix.environment }}.tfstate" \
            -input=false \
            -no-color
      
      - name: Prepare environment tfvars (repo or secrets)
        # Prefer committed per-environment tfvars. If absent (gitignored), build from
        # repository secrets: DEV_TFVARS, TEST_TFVARS, PROD_TFVARS. Do NOT print secret contents.
        env:
          REPO_TFVARS: "module9/buildOnce-deployMany/environments/${{ matrix.environment }}.tfvars"
          DEV_TFVARS: "${{ secrets.DEV_TFVARS }}"
          TEST_TFVARS: "${{ secrets.TEST_TFVARS }}"
          PROD_TFVARS: "${{ secrets.PROD_TFVARS }}"
        run: |
          set -euo pipefail
          TFVARS_PATH="$REPO_TFVARS"
          if [ -f "$TFVARS_PATH" ]; then
            echo "Using committed var-file: $TFVARS_PATH"
            echo "TFVARS_FILE=$TFVARS_PATH" >> $GITHUB_ENV
            exit 0
          fi

          echo "Committed var-file not found, attempting to create from secrets"

          case "${{ matrix.environment }}" in
            dev)
              TFVARS_CONTENT="$DEV_TFVARS"
              ;;
            test)
              TFVARS_CONTENT="$TEST_TFVARS"
              ;;
            prod)
              TFVARS_CONTENT="$PROD_TFVARS"
              ;;
            *)
              echo "Unknown environment: ${{ matrix.environment }}" >&2
              exit 1
              ;;
          esac

          if [ -z "${TFVARS_CONTENT:-}" ]; then
            echo "No tfvars content found in secrets for '${{ matrix.environment }}' - set DEV_TFVARS/TEST_TFVARS/PROD_TFVARS." >&2
            exit 1
          fi

          # Create a temp file for terraform to consume. Keep file mode private.
          TMPFILE=$(mktemp)
          umask 077
          printf '%s' "$TFVARS_CONTENT" > "$TMPFILE"
          echo "TFVARS_FILE=$TMPFILE" >> $GITHUB_ENV
      
      - name: Terraform Plan
        working-directory: ${{ env.WORKDIR }}
        id: plan
        run: |
          # Kjør plan og fang både stdout og stderr
          set +e  # Ikke stopp ved feil
          terraform plan -no-color \
            -var-file="$TFVARS_FILE" \
            -out=${{ matrix.environment }}.tfplan 2>&1 | tee plan-output.txt
          
          PLAN_EXIT_CODE=${PIPESTATUS[0]}
          set -e
          
          # Lagre output og exit code
          {
            echo "PLAN_EXIT_CODE=${PLAN_EXIT_CODE}"
            echo 'PLAN_OUTPUT<<EOF'
            cat plan-output.txt
            echo 'EOF'
          } >> "$GITHUB_ENV"
          
          exit ${PLAN_EXIT_CODE}
        continue-on-error: true
      
      - name: Comment PR with Plan
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const planOutput = process.env.PLAN_OUTPUT || 'No plan output available';
            const exitCode = process.env.PLAN_EXIT_CODE || 'unknown';
            const status = exitCode === '0' ? '✅ Success' : '❌ Failed';
            
            const output = `#### Terraform Plan for \`${{ matrix.environment }}\` 📋 ${status}
            
            <details><summary>Show Plan</summary>
            
            \`\`\`terraform
            ${planOutput}
            \`\`\`
            
            </details>
            
            **Exit Code:** ${exitCode}
            
            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Workflow: \`${{ github.workflow }}\`*`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
